# Generated by Django 3.2.9 on 2022-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('company', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('interested_in', models.CharField(max_length=150, null=True)),
                ('estimated_budget', models.CharField(max_length=150, null=True)),
                ('project_timeline', models.CharField(max_length=150, null=True)),
                ('about_us', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
