# Generated by Django 3.2.9 on 2022-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('portfolio_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Job positions',
                'verbose_name_plural': 'Job positions',
            },
        ),
    ]
